- name: Reboot ios device
  ansible.netcommon.cli_command:
    command: reload
    prompt:
    - Save?
    - confirm
    answer:
    - y
    - y

- name: Reset the connection
  ansible.builtin.meta: reset_connection

- name: Wait for the network device to reload
  ansible.builtin.wait_for_connection:
    delay: 10

- name: Get the device uptime
  vars:
    ansible_connection: network_cli
  ansible.netcommon.cli_command:
    command: "{{ platform_uptime_command[ansible_network_os] }}"
  register: output

- name: Show the device uptime
  ansible.builtin.debug:
    msg: "{{ output['stdout_lines'][0] }}"
